name: Pushing on branch !== master
on:
  push:
    branches-ignore: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetching master
        run: git fetch origin master
      - name: Cache node_modules packages
        id: node_modules_cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ runner.os }}-build-${{ runner.os }}
          path: node_modules
      - name: Audit Test
        run: npm audit --production
      - name: Install dependencies
        if: steps.node_modules_cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run Test on Affected projects
        run: npm run test:affected
  build:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetching master
        run: git fetch origin master
      - name: Cache node_modules packages
        id: node_modules_cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ runner.os }}-build-${{ runner.os }}
          path: node_modules
      - name: Install dependencies
        if: steps.node_modules_cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build code
        run: npm run build:affected