name: Node.js CI

on:
  push:
    branches-ignore: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Fetching master
        run: git fetch origin master
      - name: Install dependencies
        run: npm ci
      - name: Run Test on Affected projects
        run: npm run test:affected
